export { ProgressScreen } from '@/features/progreso/screens/ProgressScreen';
export { SettingsScreen } from './SettingsScreen';
export { LegalDocScreen } from '@/features/cuenta/screens/LegalDocScreen';
export { BorrarScreen } from '@/features/cuenta/screens/BorrarScreen';
export { DownloadsScreen } from './DownloadsScreen';
export { StuckScreen } from '@/features/atoradas/screens/StuckScreen';
export { DeckScreen } from '@/features/mazo/screens/DeckScreen';
export { DiagnosticsScreen } from './DiagnosticsScreen';
export { SfxSamplerScreen } from './SfxSamplerScreen';
